# Generated by Django 5.2.1 on 2025-05-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PropertyOwnerName', models.CharField(max_length=255)),
                ('ExistingArchiveCode', models.CharField(max_length=255)),
                ('UPIN', models.CharField(max_length=255, unique=True)),
                ('ServiceOfEstate', models.CharField(max_length=255)),
                ('placeLevel', models.CharField(max_length=255)),
                ('possessionStatus', models.CharField(max_length=255)),
                ('spaceSize', models.CharField(max_length=255)),
                ('kebele', models.CharField(max_length=255)),
                ('proofOfPossession', models.CharField(max_length=255)),
                ('DebtRestriction', models.CharField(max_length=255)),
                ('LastTaxPaymtDate', models.DateField(blank=True, null=True)),
                ('unpaidTaxDebt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('InvoiceNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('lastDatePayPropTax', models.DateField(blank=True, null=True)),
                ('unpaidPropTaxDebt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('InvoiceNumber2', models.CharField(blank=True, max_length=255, null=True)),
                ('uploadedFile', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('filePath', models.CharField(blank=True, max_length=255, null=True)),
                ('EndLeasePayPeriod', models.DateField(blank=True, null=True)),
                ('unpaidLeaseDebt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('InvoiceNumber3', models.CharField(blank=True, max_length=255, null=True)),
                ('FolderNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('Row', models.CharField(blank=True, max_length=255, null=True)),
                ('ShelfNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('NumberOfPages', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
