# Generated by Django 5.2.1 on 2025-05-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_record_created_at_record_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordfile',
            name='category',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='recordfile',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
