# Generated by Django 5.2.1 on 2025-05-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recordfile_category_recordfile_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordfile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recordfile',
            name='display_name',
        ),
    ]
