# Generated by Django 5.2.1 on 2025-05-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_recordfile_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordfile',
            name='category',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='recordfile',
            name='file_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
