# Generated by Django 5.2.1 on 2025-05-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_record_nationalid_record_phonenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='sortingNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
