# Generated by Django 5.2.1 on 2025-05-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_record_sortingnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='TotalBirr',
        ),
        migrations.AddField(
            model_name='record',
            name='FirstAmount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='SecondAmount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='ThirdAmount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
