# Generated by Django 5.2.1 on 2025-05-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_record_totalbirr_record_firstamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordfile',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
