# Generated by Django 5.2.1 on 2025-05-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_recordfile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordfile',
            name='file_hash',
            field=models.CharField(default='default_hash', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
