# Generated by Django 5.2.1 on 2025-05-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_recordfile_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordfile',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
