# Generated by Django 5.2.1 on 2025-05-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_recordfile_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordfile',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
