# Generated by Django 5.2.1 on 2025-06-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='ip',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='role',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('DOWNLOAD', 'Download'), ('VIEW', 'View'), ('OTHER', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
